// app/(root)/layout.js

import Footer from "@/components/home/Footer";
import Header from "@/components/home/Header";

export const metadata = {
  title: "Clicon - ECommerce FullStack",
  description: "Generated by create next app",
};

export default function WebLayout({ children }) {
  return (
    <div className="flex flex-col h-screen">
      <Header />
      <main className="flex-1">{children}</main>
      <Footer />
    </div>
  );
}
