// app/(root)/layout.js

import Header from "@/components/header/Header";
import BackTop from "@/components/home/BackTop";
import Footer from "@/components/home/Footer";

export const metadata = {
  title: "Clicon - ECommerce FullStack",
  description: "Generated by create next app",
};

export default function WebLayout({ children }) {
  return (
    <div className="flex flex-col h-screen">
      <Header />
      <main className="flex-1">{children}</main>
      <Footer />
      <BackTop />
    </div>
  );
}
