// app/(Dashboard)/layout.js

import Breadcrumb from "@/components/common/Breadcrumb";
import Header from "@/components/header/Header";
import Footer from "@/components/home/Footer";
import AppSidebar from "@/components/ui/app-sidebar";
import { assets } from "@/constants/assets";
import ROUTES from "@/constants/routes";

export const metadata = {
  title: "Clicon - ECommerce FullStack",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <div className="flex flex-col h-screen">
      <Header />
      {/* Top Breadcrumb */}
      <Breadcrumb
        items={[
          { label: "Home", icon: assets.House, href: ROUTES.HOME },
          { label: "User Account", href: ROUTES.SIGIN },
          { label: "Dashboard", href: ROUTES.DASHBOARD, active: true },
        ]}
      />
      <main
        className="flex-1 container pt-10 pb-18
      "
      >
        <div className="flex gap-18">
          <AppSidebar />
          <div className="flex-1 w-full">{children}</div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
