const ROUTES = {
  HOME: "/",
  SHOP: "/shop",
  PRODUCT_DETAILS: (id) => `/product-detail/${id}`,
  TRACK_ORDER: "/track-order",
  TRACK_ORDER_DETAILS: "/track-order-details",
  COMPARE: "/compare",
  WISHLIST: "/wishlist",
  SHOPING_CARD: "/shoping-card",
  CHECK_OUT: "/check-out",
  CHECK_OUT_SUCCESS: "/check-out-success",
  CHECK_OUT_FAILED: "/check-out-fail",
  FAQ: "/faqs",
  ABOUT_US: "/about-us",
  CUSTOMER_SUPPORT: "/customer-support",
  BLOG: "/blog",
  BLOG_DETAILS: (id) => `/blog-detail/${id}`,
  SIGIN: "/login",
  SIGNUP: "/signup",
  FORGET_PASSWORD: "/forget-password",
  RESET_PASSWORD: "/reset-password",
  OTP_VERIFICATION: "/otp-verification",
  EMAIL_VERIFICATION: "/email-verification",
  DASHBOARD: "/dashboard",
  ORDER_HISTORY: "/order-history",
  ORDER_HISTORY_DETAILS: (id) => `/order-history-details/${id}`,
  CARDS_ADDRESS: "/cards-address",
  BROWSING_HISTORY: "/browsing-history",
  PROFILE_SETTINGS: "/profile-settings",
};

export default ROUTES;
